# Generated by Django 2.1 on 2018-08-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='suitable',
            field=models.ManyToManyField(to='utils.EventPurpose', verbose_name='Suitable for'),
        ),
    ]
