# Generated by Django 2.1 on 2018-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180811_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='users', to='utils.Tag', verbose_name='User tags'),
        ),
    ]
