# Generated by Django 2.1 on 2018-08-12 19:13

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path, verbose_name='Profile Picture'),
        ),
    ]
