# Generated by Django 2.1 on 2018-08-13 10:18

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180812_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(blank=True, max_length=70, null=True, verbose_name='Twitter Profile')),
                ('facebook', models.CharField(blank=True, max_length=70, null=True, verbose_name='Facebook Profile')),
                ('instagram', models.CharField(blank=True, max_length=70, null=True, verbose_name='Instagram Profile')),
                ('google', models.CharField(blank=True, max_length=70, null=True, verbose_name='Google Plus Profile')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=account.models.OverwriteStorage(), upload_to=account.models.user_directory_path, verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='social',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Person'),
        ),
    ]
