# Generated by Django 2.1 on 2018-08-20 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180813_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='account.Profile', verbose_name='Person'),
        ),
    ]
