# Generated by Django 2.1 on 2018-08-15 22:39

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=events.models.directory_path, verbose_name='Poster')),
                ('main', models.BooleanField(default=False, verbose_name='Is Main')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Event poster',
                'verbose_name_plural': 'Event Posters',
            },
        ),
    ]
