# Generated by Django 2.1 on 2018-08-15 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_eventtype'),
        ('events', '0002_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Location name')),
                ('street_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street address')),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip code')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.City', verbose_name='')),
            ],
            options={
                'verbose_name': 'Event Location',
                'verbose_name_plural': 'Event Locations',
            },
        ),
    ]
