# Generated by Django 2.1 on 2018-08-16 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last Updated On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last Updated On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
    ]
