# Generated by Django 2.1 on 2018-08-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180816_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paid_for',
            field=models.BooleanField(default=False, verbose_name='Paid for'),
        ),
        migrations.AddField(
            model_name='event',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Accepted by Moderator'),
        ),
    ]
