# Generated by Django 2.1 on 2018-08-16 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180816_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'Event poster', 'verbose_name_plural': 'Posters'},
        ),
    ]
