# Generated by Django 2.1 on 2018-08-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180816_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poster',
            options={'verbose_name': 'poster', 'verbose_name_plural': 'Posters'},
        ),
    ]
