# Generated by Django 2.1 on 2018-08-13 21:37

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=artists.models.user_directory_path, verbose_name='Artist Avatar'),
        ),
    ]
