# Generated by Django 2.1 on 2018-08-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='use_profile_avatar',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
