# Generated by Django 2.1 on 2018-08-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_use_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='use_profile_avatar',
            field=models.BooleanField(default=False, verbose_name='Use profile picture as artist profile picture too'),
        ),
    ]
