# Generated by Django 2.1 on 2018-08-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20180814_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='use_profile_avatar',
            field=models.BooleanField(default=True, verbose_name='Use profile picture as artist profile picture too'),
        ),
    ]
