# Generated by Django 2.1 on 2018-08-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_auto_20180814_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='artists.Artist', verbose_name='Artist'),
        ),
    ]
