# Generated by Django 2.1 on 2018-08-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_auto_20180814_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
    ]
