# Generated by Django 2.1 on 2018-08-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_artist_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.BooleanField(default=True, verbose_name='Phone Number is on WhatsApp?'),
        ),
    ]
