# Generated by Django 2.1 on 2018-08-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_contact_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='use_profile_avatar',
            new_name='user_profile_avatar',
        ),
    ]
