# Generated by Django 2.1 on 2018-08-19 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_auto_20180819_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='user_profile_avatar',
            new_name='use_profile_avatar',
        ),
    ]
