# Generated by Django 2.1 on 2018-08-22 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_auto_20180819_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last Updated On'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated On'),
        ),
    ]
