# Generated by Django 2.1 on 2018-08-11 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Country or Area Name')),
                ('iso_code2', models.CharField(max_length=2, unique=True, verbose_name='ISO ALPHA-2 Code')),
                ('iso_code3', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='ISO ALPHA-3 Code')),
                ('iso_num', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='ISO Numeric Code UN M49 Numerical Code')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tag name')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Country', verbose_name='Country Code'),
        ),
    ]
